teams:
  enhancements-maintainers:
    description: Contributors with write access to k/enhancements
    maintainers:
    - calebamiles
    - idvoretskyi
    - jdumars
    - justaugustus
    privacy: closed
    previously:
    - features-maintainers
  kep-maintainers:
    description: KEP Process Owners
    maintainers:
    - calebamiles
    - jdumars
    - justaugustus
    privacy: closed
    previously:
    - enhancement-maintainers
