teams:
  enhancements-maintainers:
    description: Contributors with write access to k/enhancements
    maintainers:
    - calebamiles
    - idvoretskyi
    - jdumars
    - justaugustus
    privacy: closed
    previously:
    - features-maintainers
  kep-maintainers:
    description: KEP Process Owners
    maintainers:
    - calebamiles
    - jdumars
    - justaugustus
    privacy: closed
    previously:
    - enhancement-maintainers
  project-board-maintainers:
    description: Contributors with access to groom issues on org-level project boards.
      Groups can opt-in to assistance with grooming by adding this team to their
       project board with admin permissions.
    maintainers:
    - jdumars
    - justaugustus
    privacy: closed
