teams:
  cli-experimental-admins:
    description: admin access to cli-experimental
    members:
    - pwittrock
    - seans3
    - soltysh
    privacy: closed
  cli-experimental-maintainers:
    description: write access to cli-experimental
    members:
    - liggitt
    - Liujingfang1
    - monopole
    privacy: closed
  kustomize-admins:
    description: ""
    members:
    - droot
    - monopole
    - pwittrock
    privacy: closed
  kustomize-contributors:
    description: ""
    members:
    - pwittrock
    privacy: closed
  kustomize-maintainers:
    description: ""
    members:
    - pwittrock
    privacy: closed
