teams:
  sig-cluster-lifecycle:
    description: Use only if you can't figure out a better category
    maintainers:
    - luxas
    - roberthbailey
    - timothysc
    members:
    - chuckha
    - detiber
    - dixudx
    - fabriziopandini
    - jbeda
    - kad
    - karan
    - krousey
    - liztio
    - medinatiger
    - neolit123
    - pipejakob
    - rosti
    - stealthybox
    - xiangpengzhao
    - yagonobre
    privacy: closed
  sig-cluster-lifecycle-pr-reviews:
    description: ""
    maintainers:
    - luxas
    - roberthbailey
    - timothysc
    members:
    - chuckha
    - detiber
    - dixudx
    - fabriziopandini
    - jbeda
    - kad
    - karan
    - krousey
    - liztio
    - medinatiger
    - neolit123
    - pipejakob
    - rosti
    - stealthybox
    - xiangpengzhao
    - yagonobre
    - zouyee
    privacy: closed
