teams:
  kops-admins:
    description: Admin access to the kops repo
    members:
    - justinsb
    - mikedanese
    - zmerlynn
    privacy: closed
  kops-maintainers:
    description: Write access to the kops repo
    members:
    - chrislovecnm
    - geojaz
    - granular-ryanbonham
    - justinsb
    - kris-nova
    - mikedanese
    - mikesplain
    - rdrgmnzs
    - rifelpet
    - yissachar
    privacy: closed
  kubeadm-admins:
    description: Admin access to the kubeadm repo
    members:
    - luxas
    - timothysc
    privacy: closed
  kubeadm-maintainers:
    description: Write access to the kubeadm repo
    members:
    - detiber
    - fabriziopandini
    - luxas
    - neolit123
    - rosti
    - timothysc
    privacy: closed
  minikube-admins:
    description: Admin access to the minikube repo
    members:
    - balopat
    - dlorenc
    - tstromberg
    - vishh
    privacy: closed
  minikube-maintainers:
    description: Write access to the minikube repo
    members:
    - afbjorklund
    - balopat
    - ethernetdan
    - jimmidyson
    - sharifelgamal
    - tstromberg
    privacy: closed
  sig-cluster-lifecycle:
    description: Use only if you can't figure out a better category
    members:
    - chuckha
    - detiber
    - dixudx
    - ereslibre
    - fabriziopandini
    - jbeda
    - kad
    - karan
    - krousey
    - liztio
    - luxas
    - medinatiger
    - neolit123
    - pipejakob
    - rosti
    - SataQiu
    - stealthybox
    - timothysc
    - xiangpengzhao
    - yagonobre
    privacy: closed
  sig-cluster-lifecycle-pr-reviews:
    description: ""
    members:
    - chuckha
    - detiber
    - dixudx
    - ereslibre
    - fabriziopandini
    - jbeda
    - kad
    - karan
    - krousey
    - liztio
    - luxas
    - medinatiger
    - neolit123
    - pipejakob
    - rosti
    - SataQiu
    - stealthybox
    - timothysc
    - xiangpengzhao
    - yagonobre
    - zouyee
    privacy: closed
  system-validators-admins:
    description: Admin access to system-validators repo
    members:
    - neolit123
    - timothysc
    privacy: closed
  system-validators-maintainers:
    description: Write access to system-validators repo
    members:
    - neolit123
    - timothysc
    privacy: closed
