teams:
  cluster-api-provider-azure-admins:
    description: ""
    maintainers:
    - justaugustus
    privacy: closed
  cluster-api-provider-azure-maintainers:
    description: ""
    maintainers:
    - justaugustus
    members:
    - soggiest
    - tariq1890
    privacy: closed
  azuredisk-csi-driver-admins:
    description: ""
    members:
    - andyzhangx
    privacy: closed
  azuredisk-csi-driver-maintainers:
    description: ""
    members:
    - andyzhangx
    privacy: closed
  azurefile-csi-driver-admins:
    description: ""
    members:
    - andyzhangx
    privacy: closed
  azurefile-csi-driver-maintainers:
    description: ""
    members:
    - andyzhangx
    privacy: closed
