teams:
  cluster-api-provider-azure-admins:
    description: ""
    maintainers:
    - justaugustus
    privacy: closed
  cluster-api-provider-azure-maintainers:
    description: ""
    maintainers:
    - justaugustus
    members:
    - soggiest
    - tariq1890
    privacy: closed
