teams:
  sig-docs-en-owners:
    description: ""
    members:
    - Bradamant3
    - bradtopol
    - chenopis
    - cody-clark
    - jaredbhatti
    - kbarnard10
    - mistyhacks
    - ryanmcginnis
    - steveperry-53
    - stewart-yu
    - tengqm
    - tfogo
    - zacharysarah
    - zparnold
    privacy: closed
  sig-docs-en-reviews:
    description: Review PRs for English content
    members:
    - jimangel
    - Rajakavitha1
    - stewart-yu
    - xiangpengzhao
    - zacharysarah
    - zhangxiaoyu-zidif
    privacy: closed
  sig-docs-fr-owners:
    description: Owners for French content
    members:
    - abuisine
    - awkif
    - jygastaud
    - lledru
    - oussemos
    - perriea
    - rbenzair
    - rekcah78
    - sieben
    - smana
    - yastij
    privacy: closed
  sig-docs-fr-reviews:
    description: Review PRs for French content
    members:
    - abuisine
    - awkif
    - jygastaud
    - lledru
    - oussemos
    - perriea
    - rbenzair
    - rekcah78
    - sieben
    - smana
    - yastij
    privacy: closed
  sig-docs-it-owners:
    description: Owners for Italian content
    members:
    - lledru
    - micheleberardi
    - rlenferink
    privacy: closed
  sig-docs-it-reviews:
    description: Review PRs for Italian content
    members:
    - lledru
    - micheleberardi
    - rlenferink
    privacy: closed
  sig-docs-ja-owners:
    description: sig-docs-ja-owners
    members:
    - chenopis
    - cstoku
    - makocchi-git
    - MasayaAoyama
    - nasa9084
    - tnir
    privacy: closed
  sig-docs-ja-reviews:
    description: ""
    members:
    - cstoku
    - makocchi-git
    - MasayaAoyama
    - nasa9084
    - tnir
    privacy: closed
  sig-docs-ko-owners:
    description: sig-docs-ko-owners
    members:
    - ClaudiaJKang
    - gochist
    - ianychoi
    privacy: closed
  sig-docs-ko-reviews:
    description: Reviews for Korean docs PRs
    members:
    - ClaudiaJKang
    - gochist
    - ianychoi
    privacy: closed
  sig-docs-l10n-admins:
    description: Admins for l10n projects
    members:
    - Bradamant3
    - chenopis
    - ClaudiaJKang
    - cstoku
    - gochist
    - hanjiayao
    - markthink
    - tnir
    - zacharysarah
    - zhangxiaoyu-zidif
    privacy: closed
  sig-docs-maintainers:
    description: Docs maintainers team.
    members:
    - Bradamant3
    - bradtopol
    - chenopis
    - jaredbhatti
    - jimangel
    - kbarnard10
    - mistyhacks
    - pwittrock
    - ryanmcginnis
    - steveperry-53
    - tengqm
    - tfogo
    - xiangpengzhao
    - zacharysarah
    - zhangxiaoyu-zidif
    - zparnold
    privacy: closed
  sig-docs-pr-reviews:
    description: Users authorized to review docs PRs
    members:
    - Bradamant3
    - bradtopol
    - chenopis
    - cody-clark
    - jaredbhatti
    - jimangel
    - kbarnard10
    - mistyhacks
    - Rajakavitha1
    - ryanmcginnis
    - steveperry-53
    - stewart-yu
    - tengqm
    - tfogo
    - xiangpengzhao
    - zacharysarah
    - zhangxiaoyu-zidif
    - zparnold
    privacy: closed
  sig-docs-zh-owners:
    description: ""
    members:
    - hanjiayao
    - tengqm
    - xiangpengzhao
    - zhangxiaoyu-zidif
    privacy: closed
  sig-docs-zh-reviews:
    description: Reviews for Chinese docs PRs
    members:
    - chenrui333
    - idealhack
    - pigletfly
    - tengqm
    - xiangpengzhao
    - zhangxiaoyu-zidif
    privacy: closed
