teams:
  node-feature-discovery-operator-admins:
    description: Admin access to node-feature-discovery-operator repo
    members:
    - marquiz
    - zvonkok
    privacy: closed
  node-feature-discovery-operator-maintainers:
    description: Write access to node-feature-discovery-operator repo
    members:
    - marquiz
    - zvonkok
    privacy: closed
  seccomp-operator-admins:
    description: Admin access to seccomp-operator repo
    members:
    - hasheddan
    - pjbgf
    - saschagrunert
    privacy: closed
  seccomp-operator-maintainers:
    description: Write access to seccomp-operator repo
    members:
    - hasheddan
    - pjbgf
    - saschagrunert
    privacy: closed
