name: Integrations
description: Third-party integrations, webhooks, or GitHub Apps
labels: [ "area/github-integration" ]
title: "REQUEST: New integration for <org or repo>"
body:
- id: org_repo
  type: input
  attributes:
    label: Organization or Repo
    description: Which Org or Repo do you want the integration enabled on?
    placeholder: e.g. kubernetes/kubernetes
  validations:
    required: true
- id: integration_name
  type: input
  attributes:
    label: Name of integration
    placeholder: e.g. travis
  validations:
    required: true
- id: integration_site
  type: input
  attributes:
    label: Link to integration website
    placeholder: e.g. https://travis-ci.org/
  validations:
    required: true
- id: problem
  type: textarea
  attributes:
    label: Describe what is attempting to be accomplished
    placeholder: A clear and concise description of what is trying to be accomplished with this integration.
  validations:
    required: true
- id: context
  type: textarea
  attributes:
    label: Additional context for request
    placeholder: Any additional information or context to describe the use case.
  validations:
    required: false
