teams:
  sig-instrumentation-leads:
    description: ""
    members:
    - brancz
    - dashpole
    - ehashman
    - logicalhan
    privacy: closed
  sig-instrumentation-approvers:
    description: ""
    members:
    - brancz
    - dashpole
    - ehashman
    - logicalhan
    - RainbowMango
    - serathius
    privacy: closed
  sig-instrumentation-members:
    description: ""
    members:
    - 44past4
    - andyxning
    - brancz
    - coffeepac
    - danielqsj
    - dashpole
    - DirectXMan12
    - ehashman
    - kawych
    - lilic
    - loburm
    - logicalhan
    - piosz
    - RainbowMango
    - serathius
    - s-urbaniak
    - tariq1890
    - x13n
    - zouyee
    privacy: closed
