teams:
  sig-instrumentation-api-reviews:
    description: ""
    members:
    - 44past4
    - andyxning
    - brancz
    - danielqsj
    - dashpole
    - DirectXMan12
    - ehashman
    - fabxc
    - fgrzadkowski
    - kawych
    - lilic
    - loburm
    - logicalhan
    - mxinden
    - piosz
    - RainbowMango
    - s-urbaniak
    - serathius
    - tariq1890
    - x13n
    - zouyee
    privacy: closed
  sig-instrumentation-bugs:
    description: ""
    members:
    - 44past4
    - andyxning
    - brancz
    - danielqsj
    - dashpole
    - DirectXMan12
    - ehashman
    - fabxc
    - fgrzadkowski
    - kawych
    - lilic
    - loburm
    - logicalhan
    - mxinden
    - piosz
    - RainbowMango
    - s-urbaniak
    - serathius
    - tariq1890
    - x13n
    - zouyee
    privacy: closed
  sig-instrumentation-feature-requests:
    description: ""
    members:
    - 44past4
    - andyxning
    - brancz
    - danielqsj
    - dashpole
    - DirectXMan12
    - ehashman
    - fabxc
    - fgrzadkowski
    - kawych
    - lilic
    - loburm
    - logicalhan
    - mxinden
    - piosz
    - RainbowMango
    - s-urbaniak
    - serathius
    - tariq1890
    - x13n
    privacy: closed
  sig-instrumentation-misc:
    description: ""
    members:
    - 44past4
    - andyxning
    - brancz
    - danielqsj
    - dashpole
    - DirectXMan12
    - ehashman
    - fabxc
    - fgrzadkowski
    - kawych
    - lilic
    - loburm
    - logicalhan
    - mxinden
    - piosz
    - RainbowMango
    - s-urbaniak
    - serathius
    - tariq1890
    - x13n
    privacy: closed
  sig-instrumentation-pr-reviews:
    description: ""
    members:
    - 44past4
    - andyxning
    - brancz
    - danielqsj
    - dashpole
    - DirectXMan12
    - ehashman
    - fabxc
    - fgrzadkowski
    - kawych
    - lilic
    - loburm
    - logicalhan
    - mxinden
    - piosz
    - RainbowMango
    - s-urbaniak
    - serathius
    - tariq1890
    - x13n
    - zouyee
    privacy: closed
  sig-instrumentation-proposals:
    description: ""
    members:
    - 44past4
    - andyxning
    - brancz
    - danielqsj
    - dashpole
    - DirectXMan12
    - ehashman
    - fabxc
    - fgrzadkowski
    - kawych
    - lilic
    - loburm
    - logicalhan
    - mxinden
    - piosz
    - RainbowMango
    - s-urbaniak
    - serathius
    - tariq1890
    - x13n
    privacy: closed
  sig-instrumentation-test-failures:
    description: ""
    members:
    - 44past4
    - andyxning
    - brancz
    - danielqsj
    - dashpole
    - DirectXMan12
    - ehashman
    - fabxc
    - fgrzadkowski
    - kawych
    - lilic
    - loburm
    - logicalhan
    - mxinden
    - piosz
    - RainbowMango
    - s-urbaniak
    - serathius
    - tariq1890
    - x13n
    privacy: closed
