teams:
  sig-windows-bugs:
    description: For reporting and investigating bugs for sig-windows
    members:
    - alexbrand
    - feiskyer
    - jbhurat
    - michmike
    privacy: closed
  sig-windows-feature-requests:
    description: Feature requests for sig-windows
    members:
    - alexbrand
    - feiskyer
    - jbhurat
    - michmike
    privacy: closed
  sig-windows-misc:
    description: Special Interest Group Windows
    members:
    - alexbrand
    - andyzhangx
    - csrwng
    - feiskyer
    - jbhurat
    - michmike
    - pires
    - sarahnovotny
    privacy: closed
