name: Kubernetes Incubator
description: Kubernetes Incubator
default_repository_permission: read
has_organization_projects: true
has_repository_projects: true
members_can_create_repositories: false
billing_email: github@kubernetes.io
admins:
- cblecker
- fejta
- idvoretskyi
- k8s-ci-robot
- k8s-github-robot
- mrbobbytables
- nikhita
- spiffxp
- thelinuxfoundation
members:
- aaronlevy
- abhi
- adohe
- alex-mohr
- ant31
- aronchick
- arschles
- artmello
- Atoms
- aveshagarwal
- balajismaniam
- bgrant0607
- bogdando
- bowei
- Bradamant3
- bradtopol
- brancz
- bsalamat
- caesarxuchao
- calebamiles
- carolynvs
- cdrage
- chadswen
- chenopis
- childsb
- chrislovecnm
- cofyc
- ConnorDoyle
- cyphar
- davidopp
- dchen1107
- derekwaynecarr
- dhirajh
- dims
- DirectXMan12
- duglin
- eparis
- eriknelson
- euank
- feiskyer
- flyingcougar
- foxish
- grodrigues3
- hjacobs
- hongchaodeng
- humblec
- ianchakeres
- ideahitme
- idealhack
- ingvagabund
- irvifa
- janetkuo
- jberkhahn
- jboyd01
- jeremyrickard
- jimangel
- jimmidyson
- jinzhejz
- jpeeler
- jsafrane
- justaugustus
- justinsb
- k82cn
- kadel
- kawych
- kbarnard10
- kibbles-n-bytes
- kikisdeliveryservice
- krancour
- kris-nova
- krmayankk
- lavalamp
- linki
- loburm
- luksa
- luxas
- marquiz
- martinmaly
- mattymo
- mbohlool
- MHBauer
- miaoyq
- mikebrow
- mirwan
- mistyhacks
- MrHohn
- mrunalp
- msau42
- mtaufen
- mumoshu
- n3wscott
- nalind
- ncdc
- ngtuna
- nilebox
- njuettner
- nzoueidi
- onyiny-ang
- parispittman
- philips
- piosz
- piotrmiskiewicz
- pmorie
- pwittrock
- Raffo
- Rajakavitha1
- Random-Liu
- redbaron
- rhatdan
- riverzhang
- rlenferink
- roberthbailey
- rootfs
- rsmitty
- runcom
- ryanmcginnis
- sameo
- sarahnovotny
- sbezverk
- sebgoa
- serathius
- shubheksha
- slack
- Smana
- smarterclayton
- spxtr
- squat
- staebler
- steveperry-53
- stewart-yu
- sttts
- surajssd
- taragu
- tengqm
- thockin
- timothysc
- tsmetana
- vishh
- warmchang
- wongma7
- woopstar
- x13n
- xiang90
- xiangpengzhao
- xlgao-zju
- yanxuean
- yifan-gu
- yliaog
- yue9944882
- yujuhong
- zacharysarah
- zhangxiaoyu-zidif
- zmerlynn
- zparnold
teams:
  admins-kube-aws:
    description: Admin access to the kube-aws repo
    members:
    - calebamiles
    - mumoshu
    - philips
    privacy: closed
