teams:
  wg-naming:
    description: WG Naming
    members:
    - celestehorgan
    - jdumars
    - justaugustus
    privacy: closed
    teams:
      wg-naming-leads:
        description: WG Naming Leads
        members:
        - celestehorgan
        - jdumars
        - justaugustus
        privacy: closed
