teams:
  sig-scalability:
    description: SIG Scalability
    members:
    - gmarek
    - jkaniuk
    - jprzychodzen
    - krzysied
    - mborsz
    - mm4tt
    - oxddr
    - shyamjvs
    - tosi3k
    - wojtek-t
    privacy: closed
    teams:
      sig-scalability-leads:
        description: Chairs and Technical Leads for SIG Scalability
        members:
        - mm4tt
        - shyamjvs
        - wojtek-t
        privacy: closed
      sig-scalability-pr-reviews:
        description: PR reviews for SIG Scalability
        members:
        - jkaniuk
        - jprzychodzen
        - mborsz
        - mm4tt
        - shyamjvs
        - tosi3k
        - wojtek-t
        privacy: closed
